### ISSUE TITLE
Discuss issue labels

### ISSUE THREAD

**Issue by enisimsar** [bounswe/bounswe2018group5#12]
Discuss and update labels.

**Comment by enisimsar** [comment]
Base Labels are added.

**Comment by b-onc** [comment]
Nice labels - but I'm for consistency among labels. Let's remove the unneeded ones and rename the lowercase labels to capitalized.

My suggestion for removal: wontfix

**Comment by enisimsar** [comment]
I edited labels according to your opinions. @b-onc

**Comment by benescaglayan** [comment]
I recommend switching the colors of "Effort: Medium" and "Effort: Low" labels.

**Comment by b-onc** [comment]
This issue needs a deadline. I suggest 18.02, 23:59 as the deadline.

Don't forget that, Lean development means constant iteration. Nothing is fixed. If we need a new label, need to change a label's color, or change the system altogether, we can do it anytime!

**Comment by enisimsar** [comment]
Then, we can close this issue. @b-onc  👍
