### ISSUE TITLE
Create a Wiki Page for Guide about Issues, Commit and Wiki Style

### ISSUE THREAD

**Issue by iremgokceler** [bounswe/bounswe2018group5#15]

**Comment by enisimsar** [comment]
Maybe, you can add Status and Effort labels @iremgokceler. I am adding Project.

**Comment by benescaglayan** [comment]
I have added the labels @enisimsar has mentioned in order to take the snapshot of issues with our cool labelling system. I have also created a link on Wiki for you, of course you can change the title as you wish.

**Comment by b-onc** [comment]
@iremgokceler Can you make separate pages for each guide?

**Comment by iremgokceler** [comment]
Sure, I will do it as you suggested.

**Comment by iremgokceler** [comment]
I have created the Wiki pages for Issues and Commits. If you think there is a need to change anything, please feel free to make an edit on it.
