### ISSUE TITLE
Create Meeting #2 Wiki page, and Write Meeting notes

### ISSUE THREAD

**Issue by enisimsar** [bounswe/bounswe2018group5#17]
- [x] Create Meeting 2 Page 
- [x] Write Meeting Notes

**Comment by enisimsar** [comment]
Meeting 2 is added to Wiki. First draft is done for now. Meeting in Munites section will be added.

**Comment by enisimsar** [comment]
Meeting in minutes is added to Meeting Notes. Please, revise [Meeting #2 Note ](https://github.com/bounswe/bounswe2018group5/wiki/Meeting-2---14.02.2018).

**Comment by alpkaanusen** [comment]
Can we move the deadline of "Writing discuss output about project requirements to Wiki." to 23.59, 18.02.2018?

**Comment by b-onc** [comment]
Revision done. Closing issue
