### ISSUE TITLE
Document customer meeting report

### ISSUE THREAD

**Issue by eminayar** [bounswe/bounswe2018group5#19]
Create a page in wiki and write the meeting notes in detail along with our meeting agenda (i.e the questions we asked)

**Comment by b-onc** [comment]
I suggest we make the title more action-oriented, like:
Document customer meeting report

**Comment by eminayar** [comment]
Thanks for advice. I made the suggested change.

**Comment by eminayar** [comment]
Customer meeting page is done. Anyone who has time to review the page is welcome to edit.

**Comment by enisimsar** [comment]
Nice work 💯

**Comment by enisimsar** [comment]
We can change the status with completed when closing the issue.
