### ISSUE TITLE
Create Project Plan (First Draft)

### ISSUE THREAD

**Issue by iremgokceler** [bounswe/bounswe2018group5#27]

**Comment by b-onc** [comment]
It's version 1, we already finished the first draft :)

Also, I don't think the type should be wiki, but we don't have a label for project related issues. @enisimsar

**Comment by enisimsar** [comment]
It’s Project Plan and high level. So, we can change version 1 but I think before feedbacks we should you use “first draft”. 

This includes creating a wiki page and revisions.. @b-onc

**Comment by enisimsar** [comment]
First Draft is finished.
