### ISSUE TITLE
Date formating in Backend 

### ISSUE THREAD

**Issue by enisimsar** [bounswe/bounswe2018group5#276]
When sending date information, backend use yyyy-mm-ddThh:mm:ss formating. We use only yyyy-mm-dd format in frontend. Could you change these formating issue in project.deadline, project.milestones and portfolio.date? 

created at and updated at may change also.

**Comment by emingure** [comment]
project.milestones field is dictfield thus frontend has the authority to set its formatting and also type. Others are done and merged

**Comment by enisimsar** [comment]
Thanks.
