### ISSUE TITLE
Search About GitHub Auto-Labeling Bot

### ISSUE THREAD

**Issue by enisimsar** [bounswe/bounswe2018group5#28]
I cannot decide "Type" label

**Comment by benescaglayan** [comment]
Only 'Maintenance' or 'Enhancement' labels can be bounded to this issue but I think 'Enhancement' is much more applicable compared to 'Maintenance' since this is a feature that will simplify and secure our issue work.

**Comment by enisimsar** [comment]
Thank you for help

**Comment by b-onc** [comment]
Maybe we should add a `Type: Meta` label that signifies the issue/pr is repo/lecture/etc related, not the project?

**Comment by enisimsar** [comment]
I created a label `Type: Meta`  and add it to this issue. I removed `Type: Enhancement` label from this issue

**Comment by eminayar** [comment]
https://github.com/foosel/GitIssueBot
we can create a cronjob for commands to use this

**Comment by enisimsar** [comment]
the Bot changed the last label 👍
