### ISSUE TITLE
Brief Explanation and Documantation of Each Issue Label

### ISSUE THREAD

**Issue by berkan20** [bounswe/bounswe2018group5#29]

**Comment by emingure** [comment]
We can also use the description feature of labels to explain them. You can see that textbox when editing a label.

**Comment by berkan20** [comment]
I put the document under Meeting Notes/Guides.

**Comment by b-onc** [comment]
Can we move the explanation under Label System, other than creating a new page for it?

**Comment by berkan20** [comment]
It is moved under label system and added time bounds but still not sure about whether the time bounds are the ones we talked about.
