### ISSUE TITLE
Finish Requirements Version 1

### ISSUE THREAD

**Issue by b-onc** [bounswe/bounswe2018group5#31]
**DoD**

- [X] Label Functional Req as A and Non-func as B
- [X] Revise A.1.3.4.2.3
- [x] Add new entity: *Portfolio*
- [x] Extend A.2.3
- [x]  Move some sub items from tree A.1.3.4.1 up to 1.3 tree
- [x] Add Home page entity
  - from Cihat: 

    > In addition to the search mechanism, you need to include something like a browsing part. For instance, there may be a home page that shows headings like "Python" or "Translation" etc. You can think more and add requirements about a home page of both freelancers and clients. What does a user see when he/she logs in?

- [X] Delete A.1.1.5-A.1.1.7
- [X] Create subtrees for A.1.3.4.1.1 and A.1.3.4.2.1
- [x] Determine version numbers for B.2.1 
- [x] Determine API name for B.4.3
- [X] Delete B.5.6 and rename B.5.6.1 as B.5.6
- [x] Determine metrics for B.8.2
- [X] Revise B.9.1

**Comment by eminayar** [comment]
All listed tasks are completed. For further changes create another issue.
