### ISSUE TITLE
Determine and distribute mock up pages

### ISSUE THREAD

**Issue by enisimsar** [bounswe/bounswe2018group5#36]
We will determine screens according to the meeting discussion, and distribute these screens to team members.

**Comment by benescaglayan** [comment]
I have posted a question on Piazza regarding the platforms needed for mock-ups. I will let you guys know as soon as it is replied.

**Comment by enisimsar** [comment]
Done. [Task List ](https://docs.google.com/spreadsheets/d/1mmcR9Or5Pf7JUwDp-iNkGdFoLzgto4X3ECuo4_AAA9Q/edit#gid=0)
