### ISSUE TITLE
Update README for team table

### ISSUE THREAD

**Issue by iremgokceler** [bounswe/bounswe2018group5#37]

**Comment by iremgokceler** [comment]
Feel free to inform me please if you are not satisfied with the update

**Comment by b-onc** [comment]
Can we make the table take the full width of the readme page and give equal spacings to each cell?

It's better if you use full HTML and not markup with the table.

**Comment by iremgokceler** [comment]
@b-onc  I recently changed this part as you suggested. Please inform me if still there is a need to be revised
