### ISSUE TITLE
Type error during portfoglio update. 

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group5#388]
I can't exactly know what happened. But, during profile update i got the following error:

TypeError: can't convert undefined to object
componentDidUpdate
src/app/src/components/Modal/AddPortfolioModal.jsx:118

  115 | if (!getTagInProgress && !getTagHasError && getTagCompleted) {
  116 |     if (response) {
  117 |         let options = [];
> 118 |         Object.keys(search).forEach(function (key) {
      | ^  119 |             search[key].map((prop, key) => {
  120 |                 options.push({
  121 |                     label: prop.label + ": " + prop.description,

commitLifeCycles
src/app/node_modules/react-dom/cjs/react-dom.development.js:15362
commitAllLifeCycles
src/app/node_modules/react-dom/cjs/react-dom.development.js:16703
callCallback
src/app/node_modules/react-dom/cjs/react-dom.development.js:144
invokeGuardedCallbackDev
src/app/node_modules/react-dom/cjs/react-dom.development.js:193
invokeGuardedCallback
src/app/node_modules/react-dom/cjs/react-dom.development.js:243
commitRoot
src/app/node_modules/react-dom/cjs/react-dom.development.js:16879
completeRoot
src/app/node_modules/react-dom/cjs/react-dom.development.js:18335
performWorkOnRoot
src/app/node_modules/react-dom/cjs/react-dom.development.js:18257
performWork
src/app/node_modules/react-dom/cjs/react-dom.development.js:18159
performSyncWork
src/app/node_modules/react-dom/cjs/react-dom.development.js:18132
requestWork
src/app/node_modules/react-dom/cjs/react-dom.development.js:18009
scheduleWork
src/app/node_modules/react-dom/cjs/react-dom.development.js:17802
enqueueSetState
src/app/node_modules/react-dom/cjs/react-dom.development.js:12076
./node_modules/react/cjs/react.development.js/Component.prototype.setState
src/app/node_modules/react/cjs/react.development.js:404
onStateChange
src/app/node_modules/react-redux/es/components/connectAdvanced.js:245
notify
src/app/node_modules/react-redux/es/utils/Subscription.js:29
notifyNestedSubs
src/app/node_modules/react-redux/es/utils/Subscription.js:66
onStateChange
src/app/node_modules/react-redux/es/components/connectAdvanced.js:242
notify
src/app/node_modules/react-redux/es/utils/Subscription.js:29
notifyNestedSubs
src/app/node_modules/react-redux/es/utils/Subscription.js:66
onStateChange
src/app/node_modules/react-redux/es/components/connectAdvanced.js:242
notify
src/app/node_modules/react-redux/es/utils/Subscription.js:29
notifyNestedSubs
src/app/node_modules/react-redux/es/utils/Subscription.js:66
onStateChange
src/app/node_modules/react-redux/es/components/connectAdvanced.js:242
dispatch
src/app/node_modules/redux/es/redux.js:214
sagaMiddleware/</<
src/app/node_modules/redux-saga/es/internal/middleware.js:72
routerMiddleware/</</<
src/app/node_modules/connected-react-router/lib/middleware.js:40
dispatch
src/app/node_modules/redux/es/redux.js:613
wrapSagaDispatch/<
src/app/node_modules/redux-saga/es/internal/utils.js:282
runPutEffect/<
src/app/node_modules/redux-saga/es/internal/proc.js:557
exec
src/app/node_modules/redux-saga/es/internal/scheduler.js:20
flush
src/app/node_modules/redux-saga/es/internal/scheduler.js:63
asap
src/app/node_modules/redux-saga/es/internal/scheduler.js:35
runPutEffect
src/app/node_modules/redux-saga/es/internal/proc.js:553
runEffect
src/app/node_modules/redux-saga/es/internal/proc.js:496
next
src/app/node_modules/redux-saga/es/internal/proc.js:366
currCb
src/app/node_modules/redux-saga/es/internal/proc.js:449
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by enisimsar** [comment]
I resolved the problem in #390
