### ISSUE TITLE
Research for Mockup

### ISSUE THREAD

**Issue by Oguzhan09** [bounswe/bounswe2018group5#40]

**Comment by Oguzhan09** [comment]
www.ninjamock.com
www.mockflow.com
app.moqups.com
https://balsamiq.com/products/
you can use these sites. In my opinion ninjamock is easy and enough

**Comment by emingure** [comment]
https://mockflow.com/apps/wireframepro/
    - Free plan 
    - Components ready
wireframe.cc
    - No need to sign up
    - No ready components
    - For freedom of thought
https://ninjamock.com/
    - Collaboration
    - No need to sign up
    - Componens ready
    
https://balsamiq.com
    - Desktop app - No need to sign up to download and use
    - Good, enough design
    - Rich component library

I highly recommend balsamiq.com

**Comment by b-onc** [comment]
I'm closing the issue since balsamiq is decided.
