### ISSUE TITLE
Revise Requirements

### ISSUE THREAD

**Issue by b-onc** [bounswe/bounswe2018group5#69]
Per Cihat's comment:
> * I am just lazy to check the previous version of your requirements and my feedback. However, one thing just got my attention. For user requirements, it seems that you have grouped the requirements according to the "user types". It could be better if you cluster them according to the functionalities. 
> * One more comment: Instead of "the user shall be able to see", you can write them as system requirements, since seeing is not something like a user requirement :) It just sees it, if the system provides.

**Comment by b-onc** [comment]
Added some requirements

**Comment by benescaglayan** [comment]
Added some requirements.

**Comment by b-onc** [comment]
What are the "personal infos" a user will have? Let's define them, add them to glossary & be done with this issue.

**Comment by eminayar** [comment]
Moved "the user shall be able to see" requirements to under system requirements. To do so Landing Page(2.6) subtype opened.
