### ISSUE TITLE
Lack of Project Name

### ISSUE THREAD

**Issue by benescaglayan** [bounswe/bounswe2018group5#72]
It seems that our project name still not having been named has already created some minor drawbacks. What I suggest to everyone is to come up with a project name to the next meeting so that we can quickly and finally decide on one of those.

**Comment by emingure** [comment]
I am leaving the url to poll. 

https://docs.google.com/spreadsheets/d/1ps7iql9vqlocuWGJQ48F02G18UgcRnjqbFIJHdk8lMY/edit?usp=sharing

**Comment by alpkaanusen** [comment]
We have chosen "Karpuz".
